// ─── App Constants ──────────────────────────────────────────────────────────

export const APP_NAME = 'MangaVerse'
export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'

// ─── Genres ────────────────────────────────────────────────────────────────
export const GENRES = [
  { id: 'action', label: 'Action', color: '#FF4444' },
  { id: 'adventure', label: 'Adventure', color: '#FF9800' },
  { id: 'comedy', label: 'Comedy', color: '#FFD600' },
  { id: 'drama', label: 'Drama', color: '#4FC3F7' },
  { id: 'fantasy', label: 'Fantasy', color: '#9C6BFF' },
  { id: 'horror', label: 'Horror', color: '#B71C1C' },
  { id: 'mystery', label: 'Mystery', color: '#455A64' },
  { id: 'romance', label: 'Romance', color: '#FF4DA6' },
  { id: 'sci-fi', label: 'Sci-Fi', color: '#00E5FF' },
  { id: 'slice-of-life', label: 'Slice of Life', color: '#00E676' },
  { id: 'supernatural', label: 'Supernatural', color: '#7B2FFF' },
  { id: 'thriller', label: 'Thriller', color: '#FF6D00' },
  { id: 'sports', label: 'Sports', color: '#1DE9B6' },
  { id: 'mecha', label: 'Mecha', color: '#607D8B' },
  { id: 'isekai', label: 'Isekai', color: '#CE93D8' },
]

// ─── Sort Options ──────────────────────────────────────────────────────────
export const SORT_OPTIONS = [
  { value: 'popular', label: 'Most Popular' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'updated', label: 'Recently Updated' },
  { value: 'new', label: 'Newly Added' },
  { value: 'az', label: 'A → Z' },
  { value: 'za', label: 'Z → A' },
]

// ─── Status Options ────────────────────────────────────────────────────────
export const STATUS_OPTIONS = [
  { value: 'all', label: 'All Status' },
  { value: 'ongoing', label: 'Ongoing' },
  { value: 'completed', label: 'Completed' },
  { value: 'hiatus', label: 'On Hiatus' },
]

// ─── Mock Manga Data ───────────────────────────────────────────────────────
export const MOCK_MANGA = [
  {
    id: '1',
    title: 'Void Chronicles',
    titleJp: 'ヴォイドクロニクル',
    cover: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=560&fit=crop',
    genres: ['Action', 'Sci-Fi', 'Fantasy'],
    rating: 9.4,
    views: '12.4M',
    chapters: 287,
    status: 'ongoing',
    author: 'Haruki Mashima',
    description: 'In a world where the boundary between dimensions has collapsed, one warrior must traverse the infinite void to reclaim what was lost. An epic journey through fractured realities.',
    updatedAt: '2024-01-15',
    year: 2019,
    trending: true,
    featured: true,
    color: '#9C6BFF',
  },
  {
    id: '2',
    title: 'Neural Storm',
    titleJp: 'ニューラルストーム',
    cover: 'https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=400&h=560&fit=crop',
    genres: ['Sci-Fi', 'Thriller', 'Action'],
    rating: 8.9,
    views: '8.7M',
    chapters: 156,
    status: 'ongoing',
    author: 'Yuki Tanaka',
    description: 'A hacker discovers that human consciousness can be digitized — and weaponized. When the line between mind and machine dissolves, who defines reality?',
    updatedAt: '2024-01-14',
    year: 2021,
    trending: true,
    featured: false,
    color: '#4FC3F7',
  },
  {
    id: '3',
    title: 'Crimson Protocol',
    titleJp: 'クリムゾンプロトコル',
    cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=560&fit=crop',
    genres: ['Action', 'Mystery', 'Supernatural'],
    rating: 9.1,
    views: '15.2M',
    chapters: 412,
    status: 'completed',
    author: 'Ren Yoshida',
    description: 'Blood holds the secret to immortality. An ancient order will stop at nothing to keep this truth buried — until a forensic detective stumbles upon the conspiracy.',
    updatedAt: '2023-12-20',
    year: 2017,
    trending: false,
    featured: true,
    color: '#FF4444',
  },
  {
    id: '4',
    title: 'Astral Drift',
    titleJp: 'アストラルドリフト',
    cover: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&h=560&fit=crop',
    genres: ['Fantasy', 'Adventure', 'Romance'],
    rating: 8.7,
    views: '6.1M',
    chapters: 98,
    status: 'ongoing',
    author: 'Sora Miyamoto',
    description: 'Two souls separated by galaxies find each other through shared dreams. But maintaining a connection across the cosmos may cost them everything.',
    updatedAt: '2024-01-13',
    year: 2022,
    trending: true,
    featured: false,
    color: '#FF4DA6',
  },
  {
    id: '5',
    title: 'Iron Salvation',
    titleJp: 'アイアンサルベーション',
    cover: 'https://images.unsplash.com/photo-1502101872923-d48509bff386?w=400&h=560&fit=crop',
    genres: ['Mecha', 'Action', 'Drama'],
    rating: 8.5,
    views: '9.3M',
    chapters: 234,
    status: 'ongoing',
    author: 'Kenji Nakamura',
    description: 'Humanity\'s last defense against the Hollow swarm: pilots bonded to living mechs. One reluctant pilot discovers his machine has a soul — and a dark purpose.',
    updatedAt: '2024-01-12',
    year: 2020,
    trending: false,
    featured: false,
    color: '#607D8B',
  },
  {
    id: '6',
    title: 'Shadow Garden',
    titleJp: 'シャドーガーデン',
    cover: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=560&fit=crop',
    genres: ['Isekai', 'Fantasy', 'Comedy'],
    rating: 9.2,
    views: '18.9M',
    chapters: 178,
    status: 'ongoing',
    author: 'Aiko Fujiwara',
    description: 'An overpowered protagonist who pretends to be weak accidentally creates the world\'s most elite shadow organization. Now he must maintain the act across two worlds.',
    updatedAt: '2024-01-15',
    year: 2021,
    trending: true,
    featured: false,
    color: '#CE93D8',
  },
  {
    id: '7',
    title: 'Phantom Frequency',
    titleJp: 'ファントムフリークエンシー',
    cover: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&h=560&fit=crop',
    genres: ['Horror', 'Thriller', 'Supernatural'],
    rating: 8.8,
    views: '5.4M',
    chapters: 89,
    status: 'ongoing',
    author: 'Takeshi Morimoto',
    description: 'A radio station that broadcasts from the frequency between life and death. Those who tune in hear the voices of the recently departed — with urgent, unfinished messages.',
    updatedAt: '2024-01-11',
    year: 2023,
    trending: false,
    featured: false,
    color: '#B71C1C',
  },
  {
    id: '8',
    title: 'Cascade Bloom',
    titleJp: 'カスケードブルーム',
    cover: 'https://images.unsplash.com/photo-1490750967868-88df5691cc03?w=400&h=560&fit=crop',
    genres: ['Slice of Life', 'Romance', 'Drama'],
    rating: 8.6,
    views: '4.2M',
    chapters: 67,
    status: 'ongoing',
    author: 'Hana Watanabe',
    description: 'A florist with synesthesia experiences emotions as colors and textures. When a colorblind architect walks into her shop, they begin to see the world through each other\'s eyes.',
    updatedAt: '2024-01-10',
    year: 2023,
    trending: false,
    featured: false,
    color: '#00E676',
  },
]

// Mock chapters
export const MOCK_CHAPTERS = Array.from({ length: 50 }, (_, i) => ({
  id: `ch-${50 - i}`,
  number: 50 - i,
  title: i % 7 === 0 ? `Chapter ${50 - i}: The Awakening` : `Chapter ${50 - i}`,
  pages: Math.floor(Math.random() * 20) + 18,
  uploadedAt: new Date(Date.now() - i * 3 * 24 * 60 * 60 * 1000).toISOString(),
  viewed: i > 40,
}))

// Mock comments
export const MOCK_COMMENTS = [
  {
    id: 'c1',
    user: { name: 'NeonWatcher', avatar: null, level: 42 },
    text: 'The art style in chapter 280 completely blew me away. The panel composition is masterful.',
    likes: 234,
    createdAt: '2024-01-14T10:30:00Z',
    replies: 12,
  },
  {
    id: 'c2',
    user: { name: 'VoidDrifter_X', avatar: null, level: 17 },
    text: 'Finally caught up after 3 days of binge reading. My sleep schedule is destroyed but worth it.',
    likes: 189,
    createdAt: '2024-01-13T22:15:00Z',
    replies: 8,
  },
  {
    id: 'c3',
    user: { name: 'MangaLore99', avatar: null, level: 88 },
    text: 'The foreshadowing in volume 8 about the antagonist\'s true nature. It was there all along.',
    likes: 156,
    createdAt: '2024-01-13T18:45:00Z',
    replies: 23,
  },
  {
    id: 'c4',
    user: { name: 'SakuraFrost', avatar: null, level: 31 },
    text: 'The way the author handles grief is so real and raw. Rarely see this in manga.',
    likes: 98,
    createdAt: '2024-01-12T14:20:00Z',
    replies: 4,
  },
]

// Reader mock pages
export const MOCK_PAGES = Array.from({ length: 24 }, (_, i) => ({
  id: `page-${i + 1}`,
  number: i + 1,
  url: `https://picsum.photos/seed/${i + 100}/800/1200`,
  width: 800,
  height: 1200,
}))
