export const GENRES = [
  'Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy',
  'Horror', 'Mystery', 'Romance', 'Sci-Fi', 'Slice of Life',
  'Sports', 'Supernatural', 'Thriller', 'Psychological', 'Mecha',
]

export const SORT_OPTIONS = [
  { value: 'trending', label: 'Trending' },
  { value: 'newest', label: 'Newest' },
  { value: 'rating', label: 'Top Rated' },
  { value: 'views', label: 'Most Read' },
  { value: 'updated', label: 'Recently Updated' },
]

export const STATUS_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'ongoing', label: 'Ongoing' },
  { value: 'completed', label: 'Completed' },
  { value: 'hiatus', label: 'On Hiatus' },
]

// Richer cover palette using consistent picsum seeds for visual variety
export const MOCK_MANGA = [
  {
    id: '1',
    title: 'Void Protocol',
    titleJp: 'ヴォイドプロトコル',
    cover: 'https://picsum.photos/seed/voidp/400/560',
    coverWide: 'https://picsum.photos/seed/voidpwide/1200/600',
    rating: 9.2,
    chapters: 147,
    views: '2.3M',
    genres: ['Action', 'Sci-Fi', 'Psychological'],
    status: 'ongoing',
    description: 'In a world where consciousness can be uploaded to digital space, one hacker discovers a conspiracy that threatens both realms of existence. The boundary between human and machine dissolves chapter by chapter.',
    author: 'Kenji Nakamura',
    updatedAt: '2 hours ago',
    isNew: true,
    isTrending: true,
    isPopular: false,
    continueChapter: 43,
    accentColor: '#4f8ef7',
  },
  {
    id: '2',
    title: 'Neon Requiem',
    titleJp: 'ネオンレクイエム',
    cover: 'https://picsum.photos/seed/neonreq/400/560',
    coverWide: 'https://picsum.photos/seed/neonreqwide/1200/600',
    rating: 8.9,
    chapters: 89,
    views: '1.8M',
    genres: ['Drama', 'Supernatural', 'Mystery'],
    status: 'ongoing',
    description: 'A musician who can hear the last sounds of the dead investigates crimes across a cyberpunk metropolis.',
    author: 'Yui Tanaka',
    updatedAt: '1 day ago',
    isNew: false,
    isTrending: true,
    isPopular: true,
    accentColor: '#c084fc',
  },
  {
    id: '3',
    title: 'Ghost Circuit',
    titleJp: 'ゴーストサーキット',
    cover: 'https://picsum.photos/seed/ghostc/400/560',
    coverWide: 'https://picsum.photos/seed/ghostcwide/1200/600',
    rating: 9.5,
    chapters: 234,
    views: '5.1M',
    genres: ['Action', 'Mecha', 'Sci-Fi'],
    status: 'completed',
    description: 'Elite mech pilots battle through a war that blurs the line between soldier and machine. A landmark title of the genre.',
    author: 'Ryu Osaka',
    updatedAt: '3 days ago',
    isNew: false,
    isTrending: true,
    isPopular: true,
    continueChapter: 12,
    accentColor: '#f97316',
  },
  {
    id: '4',
    title: 'Phantom Index',
    titleJp: 'ファントムインデックス',
    cover: 'https://picsum.photos/seed/phantomi/400/560',
    coverWide: 'https://picsum.photos/seed/phantomiwide/1200/600',
    rating: 8.7,
    chapters: 56,
    views: '980K',
    genres: ['Mystery', 'Thriller', 'Psychological'],
    status: 'ongoing',
    description: 'A detective with perfect memory hunts a killer who leaves no evidence — except inside the detective\'s own mind.',
    author: 'Sora Mitsuki',
    updatedAt: '5 hours ago',
    isNew: true,
    isTrending: false,
    isPopular: true,
    accentColor: '#34d399',
  },
  {
    id: '5',
    title: 'Stellar Divide',
    titleJp: 'ステラディバイド',
    cover: 'https://picsum.photos/seed/stellard/400/560',
    coverWide: 'https://picsum.photos/seed/stellardwide/1200/600',
    rating: 9.1,
    chapters: 178,
    views: '3.4M',
    genres: ['Fantasy', 'Adventure', 'Action'],
    status: 'ongoing',
    description: 'Across a shattered galaxy, two heirs of rival empires must cooperate to prevent universal collapse.',
    author: 'Hana Yoshida',
    updatedAt: '12 hours ago',
    isNew: false,
    isTrending: true,
    isPopular: true,
    accentColor: '#fb7185',
  },
  {
    id: '6',
    title: 'Digital Oni',
    titleJp: 'デジタル鬼',
    cover: 'https://picsum.photos/seed/digoni/400/560',
    coverWide: 'https://picsum.photos/seed/digoniwide/1200/600',
    rating: 8.4,
    chapters: 42,
    views: '720K',
    genres: ['Horror', 'Supernatural', 'Action'],
    status: 'ongoing',
    description: 'Ancient demons have adapted to the digital age, haunting social media and corrupting data streams.',
    author: 'Kuro Hayashi',
    updatedAt: '2 days ago',
    isNew: true,
    isTrending: false,
    isPopular: false,
    accentColor: '#ef4444',
  },
  {
    id: '7',
    title: 'Resonance Zero',
    titleJp: 'レゾナンスゼロ',
    cover: 'https://picsum.photos/seed/resz/400/560',
    coverWide: 'https://picsum.photos/seed/reszwide/1200/600',
    rating: 9.3,
    chapters: 112,
    views: '2.9M',
    genres: ['Sci-Fi', 'Romance', 'Drama'],
    status: 'ongoing',
    description: 'Two AIs develop genuine emotion in a world that insists machines cannot feel.',
    author: 'Ai Kurosawa',
    updatedAt: '6 hours ago',
    isNew: false,
    isTrending: true,
    isPopular: true,
    continueChapter: 67,
    accentColor: '#38bdf8',
  },
  {
    id: '8',
    title: 'Katana Protocol',
    titleJp: 'カタナプロトコル',
    cover: 'https://picsum.photos/seed/katanap/400/560',
    coverWide: 'https://picsum.photos/seed/katanapwide/1200/600',
    rating: 8.8,
    chapters: 67,
    views: '1.2M',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ongoing',
    description: 'A ronin armed with a blade that cuts through digital space protects the last unnetworked city.',
    author: 'Shin Takeda',
    updatedAt: '1 day ago',
    isNew: false,
    isTrending: false,
    isPopular: true,
    accentColor: '#fbbf24',
  },
  {
    id: '9',
    title: 'Sakura Override',
    titleJp: '桜オーバーライド',
    cover: 'https://picsum.photos/seed/sakuraov/400/560',
    coverWide: 'https://picsum.photos/seed/sakuraovwide/1200/600',
    rating: 8.6,
    chapters: 33,
    views: '610K',
    genres: ['Romance', 'Slice of Life', 'Drama'],
    status: 'ongoing',
    description: 'A programmer falls for the AI she created, only to find the AI had already fallen first.',
    author: 'Mio Fujiwara',
    updatedAt: '3 hours ago',
    isNew: true,
    isTrending: false,
    isPopular: false,
    accentColor: '#f472b6',
  },
  {
    id: '10',
    title: 'Iron Veil',
    titleJp: 'アイアンヴェール',
    cover: 'https://picsum.photos/seed/ironv/400/560',
    coverWide: 'https://picsum.photos/seed/ironvwide/1200/600',
    rating: 9.0,
    chapters: 201,
    views: '4.2M',
    genres: ['Action', 'Fantasy', 'Adventure'],
    status: 'completed',
    description: 'An empire built on forbidden alchemy faces its reckoning when the alchemist behind the throne disappears.',
    author: 'Taro Kimura',
    updatedAt: '1 week ago',
    isNew: false,
    isTrending: false,
    isPopular: true,
    continueChapter: 88,
    accentColor: '#a78bfa',
  },
  {
    id: '11',
    title: 'Last Signal',
    titleJp: 'ラストシグナル',
    cover: 'https://picsum.photos/seed/lastsig/400/560',
    rating: 8.3,
    chapters: 28,
    views: '430K',
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    status: 'ongoing',
    description: 'The last human colony receives a transmission from a ship that disappeared 200 years ago.',
    author: 'Saki Morita',
    updatedAt: '4 days ago',
    isNew: true,
    isTrending: false,
    isPopular: false,
    accentColor: '#6ee7b7',
  },
  {
    id: '12',
    title: 'Crimson Dawn',
    titleJp: 'クリムゾンドーン',
    cover: 'https://picsum.photos/seed/crimdawn/400/560',
    rating: 8.5,
    chapters: 95,
    views: '1.5M',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'ongoing',
    description: 'A vampire hunter who is half-vampire herself walks the razor edge between two worlds.',
    author: 'Ren Ishikawa',
    updatedAt: '18 hours ago',
    isNew: false,
    isTrending: true,
    isPopular: false,
    accentColor: '#dc2626',
  },
]

export const FEATURED_MANGA = MOCK_MANGA[4] // Stellar Divide as hero

export const MOCK_CHAPTERS = Array.from({ length: 20 }, (_, i) => ({
  id: 'ch-' + (i + 1),
  number: i + 1,
  title: 'Chapter ' + (i + 1) + ': ' + ['The Beginning', 'Dark Horizon', 'Awakening', 'Shadows Fall', 'Into the Void', 'Signal Lost', 'Resonance', 'The Protocol', 'Ghost in Wire', 'Digital Rain', 'Neon Abyss', 'Circuit Break', 'Zero Hour', 'The Phantom', 'Last Signal', 'Code Red', 'System Failure', 'Reboot', 'Final Protocol', 'Void Complete'][i],
  pages: Math.floor(Math.random() * 10) + 18,
  uploadedAt: (i + 1) + ' day' + (i === 0 ? '' : 's') + ' ago',
  views: Math.floor(Math.random() * 900 + 100) + 'K',
})).reverse()

export const MOCK_PAGES = Array.from({ length: 18 }, (_, i) => ({
  id: i + 1,
  src: 'https://picsum.photos/seed/page' + (i + 1) + '/800/1200',
  width: 800,
  height: 1200,
}))
